### ISSUE TITLE
is it possible to add complex feature support?

### ISSUE THREAD

**Issue by yunfan** [adafruit/micropython-adafruit-rgb-display#3]
hello, thanks for developing such useful library, with it, i could easilly do simple drawing now. but there are still some problems bores me, i am using a esp32 board, with micropython flashed, and a ili9341 display wired on soft spi

1, the drawing speed, its a bit slow that i could see the drawing line one by one while filling the screen, but the board i use has a default demo showing that it could easilly support animation. so i guess there might be so improve space of the performance. some guys said i need to write the register and screen ram directly, but the library dont support that

2, my lcd use the type 3 screen direction as default , so each drawing's x start from right to left, i want to fix that, but again, the library dont support that

hope you could finally add the complex feature i need.

**Comment by deshipu** [comment]
You can write directly to the display's registers using the `_write` method, and you can write to the display's memory using the `_block` method.

**Comment by yunfan** [comment]
ok trying
