### ISSUE TITLE
Typo in list of supported displays: ILI9241

### ISSUE THREAD

**Issue by Sakartu** [adafruit/micropython-adafruit-rgb-display#5]
In the list of supported displays, there is a typo in the class name for the ili9342, it says "ILI9241"

**Comment by deshipu** [comment]
Well spotted! Do you want to make a pull request to fix it?

**Comment by deshipu** [comment]
Wait a minute, we don't support either ILI9342 nor ILI9241. We only support ILI9341.

**Comment by Sakartu** [comment]
Oops, I made a typo in my comment as well :smiley: 

Anyway, I just created a PR #6

**Comment by deshipu** [comment]
Thanks a lot, it's merged!
